name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.1.1
  meta: ^1.3.0
  path: ^1.8.0
  flutter_math_fork: 0.7.2
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.10+1

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

environment:
  sdk: '^3.4.0'
